---
- name: Be sure ntp daemon is installed
  apt:
    name=ntp
    state=installed
  become: yes
  tags: ntp

- name: Change timezone
  copy:
    src=/usr/share/zoneinfo/{{ TIMEZONE }}
    dest=/etc/localtime
    force=yes
  become: yes
  tags: ntp

- name: Write to hardware
  command: 'hwclock -w'
  run_once: true
  become: yes
  tags: ntp

- name: Be sure ntp daemon is running and enabled
  service:
    name=ntp
    state=running
    enabled=yes
  become: yes
  tags: ntp

- name: Check System Time
  command: 'date'
  register: time_result
  become: yes
  tags: ntp

- name: Check timestamp
  debug: msg={{ time_result.stdout_lines }}
  tags: ntp
