sudo: required
install:
    - sudo apt-get update
    - sudo apt-get install -y software-properties-common
    - sudo apt-add-repository -y ppa:ansible/ansible
    - sudo apt-get update
    - sudo apt-get install -y ansible
    - ansible --version
    - sudo sed -i "s/onos_build_machine/$MASTER_HOSTNAME/g" hosts
    - sudo ansible-playbook -i hosts playbook.yml --connection=local
