---
- name: Set variable for ONOS
  set_fact:
    ONOS_REPOS: "https://github.com/opennetworkinglab/onos"
  tags: onos

- name: Clone ONOS
  git:
    repo: "{{ ONOS_REPOS }}"
    dest: "{{ ONOS_ROOT }}"
    update: no
    accept_hostkey: true
    force: no
  tags: onos

- name: Build ONOS
  args:
    chdir: "{{ ONOS_ROOT }}"
  command: "{{ M2_HOME }}/bin/mvn clean install"
  tags: onos

- name: Packing ONOS Tarball
  args:
    chdir: "{{ ONOS_ROOT }}"
  command: "{{ ONOS_ROOT }}/tools/build/onos-package"
  tags: onos

- name: Append enviroment variables in bashrc
  template:
    src: "onos_env.j2"
    dest: "~/.onos_env"
    mode: 0444
  tags:
    - onos
    - bashrc

- name: Append source file in bashrc
  lineinfile:
    dest: "~/.bashrc"
    line: "source ~/.onos_env"
    mode: 0644
  tags:
    - onos
    - bashrc
